apiVersion: v1
kind: Service
metadata:
  name: smartpharmacy-api
  labels:
    app: smartpharmacy
    tier: api
spec:
  type: ClusterIP
  selector:
    app: smartpharmacy
    tier: api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http