apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpharmacy-web
  labels:
    app: smartpharmacy
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: smartpharmacy
      tier: web
  template:
    metadata:
      labels:
        app: smartpharmacy
        tier: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.web.resources.requests.cpu }}
              memory: {{ .Values.web.resources.requests.memory }}
            limits:
              cpu: {{ .Values.web.resources.limits.cpu }}
              memory: {{ .Values.web.resources.limits.memory }}
      terminationGracePeriodSeconds: 30