apiVersion: v1
kind: Service
metadata:
  name: smartpharmacy-web
  labels:
    app: smartpharmacy
    tier: web
spec:
  type: ClusterIP
  selector:
    app: smartpharmacy
    tier: web
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http